language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm install
  - bower install
  - gulp test --verbose

cache:
  directories:
  - bower_components
  - node_modules
